# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["grant@stephens.co.za"]
cloned_from = "https://github.com/fastly/compute-starter-kit-go-tinygo"
description = ""
language = "go"
manifest_version = 3
name = "windash-big-go"
service_id = "nqSA4bttH0mRZ7Ab3mmcC5"

[local_server]
[local_server.backends]
[local_server.backends.vensys]
url = "https://api.vensys.de:8443"
[local_server.backends.vensys-cached]
url = "https://vensys.global.ssl.fastly.net"
[local_server.secret_stores]
vensys-secret = { file = 'secret.json', format = 'json' }
[local_server.kv_stores]
vensys-data = { file = 'data.json', format = 'json' }


[scripts]
# build = "tinygo build -target=wasi -o bin/main.wasm ./"
build = "go build -o bin/main.wasm ./"
env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
post_init = "go get github.com/fastly/compute-sdk-go@latest"
[localserver]
